name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Prepare models
      run: python prepare_models.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Build executable
      run: python build_windows.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MonitorOCR-Windows
        path: release/
        retention-days: 30
