name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Cache EasyOCR models
      uses: actions/cache@v3
      with:
        path: ~/.EasyOCR
        key: ${{ runner.os }}-easyocr-models-v1
        restore-keys: |
          ${{ runner.os }}-easyocr-models-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Prepare EasyOCR and PaddleOCR models
      run: |
        python prepare_models_easyocr.py || python prepare_models.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Build executable with EasyOCR
      run: python build_windows_easyocr.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MonitorOCR-Windows-EasyOCR
        path: release/
        retention-days: 30
