name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    # 不再缓存EasyOCR模型，用户手动下载
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      env:
        PYTHONIOENCODING: utf-8
    
    # EasyOCR模型不再打包，用户使用时手动下载
    
    - name: Test packaging configuration
      run: |
        python test_packaging_config.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Build executable with EasyOCR and models
      run: |
        python build_windows_with_models.py
      env:
        PYTHONIOENCODING: utf-8
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MonitorOCR-Windows-EasyOCR
        path: release/
        retention-days: 30
